Traceback (most recent call last):
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/client.py", line 626, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
<<<<<<< HEAD
  File "/home/cd96/anaconda3/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/cd96/anaconda3/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/cd96/anaconda3/envs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from palettable.cubehelix import Cubehelix
palette = Cubehelix.make(start=-0.5, rotation=0.3,reverse=True,n=10)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/tmp/ipykernel_11292/4023577175.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mpalettable[0m[0;34m.[0m[0mcubehelix[0m [0;32mimport[0m [0mCubehelix[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mpalette[0m [0;34m=[0m [0mCubehelix[0m[0;34m.[0m[0mmake[0m[0;34m([0m[0mstart[0m[0;34m=[0m[0;34m-[0m[0;36m0.5[0m[0;34m,[0m [0mrotation[0m[0;34m=[0m[0;36m0.3[0m[0;34m,[0m[0mreverse[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m[0mn[0m[0;34m=[0m[0;36m10[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'palettable'
ModuleNotFoundError: No module named 'palettable'
=======
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/client.py", line 838, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/client.py", line 650, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/jebarrios/anaconda3/envs/kwant/lib/python3.6/site-packages/nbclient/client.py", line 698, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['k=[[0,0],[0.5,0],[1.0,0]]', 'k_label1=[r"$\\Gamma$",r"$Y$",r"$\\Gamma$"]', '(k_vec,k_dist,k_node)=NX_WSM.k_path(k,501, report=False)', 'EkfinX10=NX_WSM.solve_all(k_vec)', '']
...
['', 'k=[[0,0],[0.5,0],[1.0,0]]', 'k_label3=[r"$\\Gamma$",r"$X$",r"$\\Gamma$"]', '(k_vec,k_dist,k_node)=NZ_WSM.k_path(k,501, report=False)', 'EkfinZ10=NZ_WSM.solve_all(k_vec)']
-------------------
>>>>>>> 8d10c34345d3e6edb61b9525a2e7c8c6a5ac7485

